n=str(input("Type in your name: "))
p=str(input("Which place you are from: "))
print("Hello",n,"How is the weather in",p)
age=int(input("What is your age: "))
print("am i right, This is",n,"aged",age,"from",p,)